# ── LND (regtest) ───────────────────────────────────────────

[Application Options]
# Network
debuglevel=info

# Listen
rpclisten=0.0.0.0:10009
restlisten=0.0.0.0:8081

# TLS
tlsextradomain=lnd
tlsextraip=0.0.0.0

# No backup / no bootstrap
noseedbackup=1
nobootstrap=1

[Bitcoin]
bitcoin.regtest=1
bitcoin.node=bitcoind

[Bitcoind]
bitcoind.rpcuser=bitcoin
bitcoind.rpcpass=bitcoin
bitcoind.rpchost=bitcoin:18443
bitcoind.zmqpubrawblock=tcp://bitcoin:28332
bitcoind.zmqpubrawtx=tcp://bitcoin:28333
